
  function seatRange(seats){if(!seats?.length)return"—";const s=[...seats].sort((a,b)=>a-b).map(i=>"S"+(i+1));return s.length===1?s[0]:s[0]+"–"+s.at(-1)}
  function filteredGuests(event){const q=ui.guestQuery.trim().toLocaleLowerCase("tr");return event.guests.filter(g=>{const t=g.assignment&&event.tables.find(x=>x.id===g.assignment.tableId),hay=[g.name,g.vip,g.invitedBy,g.notes,t?.number,g.planningStatus].join(" ").toLocaleLowerCase("tr");let filter=true;if(ui.guestFilter==="assigned")filter=!!g.assignment;if(ui.guestFilter==="unassigned")filter=!g.assignment;if(ui.guestFilter==="confirmed")filter=g.planningStatus==="Confirmed";if(ui.guestFilter==="tentative")filter=g.planningStatus==="Tentative";return(!q||hay.includes(q))&&filter})}
  function guestsHTML(event){const guests=filteredGuests(event);return`<div class="screen-scroll"><div class="screen-inner"><div class="screen-titlebar"><div><h2>${t("guests.title")}</h2><p>${t("guests.recordsSummary",{records:event.guests.length,total:eventMetrics(event).guests})}</p></div><div class="toolbar-row"><input class="filter-input" id="guestSearch" value="${esc(ui.guestQuery)}" placeholder="${t("guests.search")}"><select class="filter-input" id="guestFilter" style="width:128px"><option value="all">${t("guests.filter.all")}</option><option value="assigned" ${ui.guestFilter==="assigned"?"selected":""}>${t("guests.filter.assigned")}</option><option value="unassigned" ${ui.guestFilter==="unassigned"?"selected":""}>${t("guests.filter.unassigned")}</option><option value="confirmed" ${ui.guestFilter==="confirmed"?"selected":""}>${t("guests.filter.confirmed")}</option><option value="tentative" ${ui.guestFilter==="tentative"?"selected":""}>${t("guests.filter.tentative")}</option></select><button class="btn" data-guest-command="template">${icon("download")}${t("guests.excelTemplate")}</button><button class="btn" data-guest-command="import">${icon("image")}${t("guests.importExcel")}</button><button class="btn primary" data-guest-command="add">${icon("plus")}${t("guests.addGuest")}</button></div></div><div class="guest-shell"><table class="guest-table"><thead><tr><th>${t("guests.col.name")}</th><th>${t("guests.col.pax")}</th><th>${t("guests.col.status")}</th><th>${t("guests.col.vip")}</th><th>${t("guests.col.invitedBy")}</th><th>${t("guests.col.table")}</th><th>${t("guests.col.seat")}</th><th>${t("guests.col.notes")}</th><th>${t("guests.col.actions")}</th></tr></thead><tbody>${guests.length?guests.map(g=>guestRowHTML(event,g)).join(""):`<tr><td colspan="9" style="height:90px;text-align:center;color:var(--muted)">${t("guests.noMatches")}</td></tr>`}</tbody></table></div></div></div>`}
  function guestRowHTML(event,g){const t_=g.assignment&&event.tables.find(x=>x.id===g.assignment.tableId);return`<tr><td><span class="guest-name">${esc(g.name)}</span>${additionalOf(g)?`<span class="additional-note">${t("guests.additionalNote",{n:additionalOf(g),pax:paxOf(g)})}</span>`:""}</td><td class="mono">${paxOf(g)}</td><td><span class="status-chip ${g.planningStatus.toLowerCase()}">${esc(t("status.planning."+g.planningStatus))}</span></td><td><span class="vip-mark ${g.vip.toLowerCase()}">${esc(g.vip)}</span></td><td>${esc(g.invitedBy||"—")}</td><td>${t_?`<b>${esc(t_.number)}</b>${g.assignment.locked?" · 🔒":""}`:`<span class='muted'>${t("guests.unassigned")}</span>`}</td><td>${g.assignment?seatRange(g.assignment.seats):"—"}</td><td title="${esc(g.notes)}">${esc((g.notes||"—").slice(0,34))}</td><td><div class="row-actions"><button class="row-action" title="Open in Seating" data-guest-seat="${g.id}">${icon("seat")}</button><button class="row-action" title="Edit guest" data-guest-edit="${g.id}">${icon("edit")}</button><button class="row-action" title="Delete guest" data-guest-delete="${g.id}">${icon("trash")}</button></div></td></tr>`}
  function bindGuests(){const search=document.getElementById("guestSearch");search.oninput=()=>{ui.guestQuery=search.value;const p=search.selectionStart;render();requestAnimationFrame(()=>{const n=document.getElementById("guestSearch");n?.focus();n?.setSelectionRange(p,p)})};document.getElementById("guestFilter").onchange=e=>{ui.guestFilter=e.target.value;render()};app.querySelector("[data-guest-command='add']").onclick=()=>openGuestDialog();app.querySelector("[data-guest-command='import']").onclick=openExcelWizard;app.querySelector("[data-guest-command='template']").onclick=downloadExcelTemplate;app.querySelectorAll("[data-guest-edit]").forEach(b=>b.onclick=()=>openGuestDialog(b.dataset.guestEdit));app.querySelectorAll("[data-guest-delete]").forEach(b=>b.onclick=()=>deleteGuest(b.dataset.guestDelete));app.querySelectorAll("[data-guest-seat]").forEach(b=>b.onclick=()=>focusGuest(b.dataset.guestSeat))}
  function parseCompactName(value){const raw=String(value||"").trim(),match=raw.match(/^(.*?)\s*\+\s*(\d+)\s*$/);return match?{name:match[1].trim(),additionalGuests:Number(match[2]),detected:true}:{name:raw,additionalGuests:0,detected:false}}
  function openGuestDialog(id=null){const form=document.getElementById("guestForm"),fields=form.elements,g=id?activeEvent().guests.find(x=>x.id===id):null;form.reset();fields.id.value=g?.id||"";fields.name.value=g?.name||"";fields.additionalGuests.value=additionalOf(g||{pax:1});fields.planningStatus.value=g?.planningStatus||"Confirmed";fields.vip.value=g?.vip||"Standard";fields.invitedBy.value=g?.invitedBy||"";fields.notes.value=g?.notes||"";document.getElementById("guestTotalPax").textContent=String(paxOf(g||{pax:1}));document.getElementById("guestDialogTitle").textContent=g?"Edit Guest":"Add Guest";document.getElementById("guestDialog").showModal();setTimeout(()=>fields.name.focus(),30)}
  document.getElementById("guestForm").elements.additionalGuests.addEventListener("input",e=>document.getElementById("guestTotalPax").textContent=String(1+Math.max(0,Number(e.target.value)||0)));
  document.getElementById("guestForm").addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.currentTarget),event=activeEvent(),id=f.get("id"),existing=event.guests.find(g=>g.id===id),compact=parseCompactName(f.get("name"));let additional=Math.max(0,Number(f.get("additionalGuests"))||0);if(compact.detected&&additional===0)additional=compact.additionalGuests;const pax=1+additional;if(!compact.name){toast("Name Surname is required.","error");return}if(existing?.assignment){const t=event.tables.find(x=>x.id===existing.assignment.tableId),others=tableAssignedPax(event,t.id)-paxOf(existing);if(others+pax>t.capacity){toast(`${t.number} has only ${t.capacity-others} seats available for this record.`,"error");return}existing.additionalGuests=additional;existing.pax=pax;repackTableAssignments(event,t,t.capacity)}const data={name:compact.name,additionalGuests:additional,pax,planningStatus:f.get("planningStatus"),vip:f.get("vip"),invitedBy:String(f.get("invitedBy")).trim(),notes:String(f.get("notes")).trim()};if(existing)Object.assign(existing,data);else event.guests.unshift({id:uid("guest"),...data,arrivalStatus:"Not Arrived",assignment:null,createdAt:nowISO()});touchEvent(event);document.getElementById("guestDialog").close();render();toast(existing?"Guest updated.":"Guest added.","success")});
  function deleteGuest(id){const event=activeEvent(),g=event.guests.find(x=>x.id===id);if(!g||!confirm(`Delete ${g.name} from the guest list?`))return;event.guests=event.guests.filter(x=>x.id!==id);touchEvent(event);render();toast("Guest deleted.")}

  function wizardStepsHTML(step){const labels=["Choose File","Source Preview","Column Mapping","Interpretation","Summary"];return`<div class="wizard-steps">${labels.map((l,i)=>`<div class="wizard-step ${step===i+1?"active":step>i+1?"done":""}"><i>${step>i+1?"✓":i+1}</i><span>${l}</span></div>`).join("")}</div>`}
  function openExcelWizard(){pendingImport={step:1,fileName:"",rows:[],headers:[],mapping:{},interpreted:[]};renderExcelWizard();document.getElementById("excelDialog").showModal()}
  function renderExcelWizard(){const root=document.getElementById("excelWizard"),p=pendingImport;if(!p)return;root.innerHTML=`<div class="dialog-head"><h2>Import Guest List</h2><button class="dialog-close" data-wizard-close aria-label="Close">×</button></div>${wizardStepsHTML(p.step)}<div class="dialog-body">${wizardBodyHTML(p)}</div><div class="dialog-foot">${wizardFootHTML(p)}</div>`;bindExcelWizard()}
  function wizardBodyHTML(p){if(p.step===1)return`<div class="drop-zone">${icon("download")}<h3>Choose Excel or CSV file</h3><p>Nothing is imported until you review source rows, mapping and interpretation.</p><div class="toolbar-row"><button class="btn" data-wizard-template>${icon("download")}Download Excel Template</button><button class="btn primary" data-wizard-choose>${icon("plus")}Choose File</button></div></div>`;if(p.step===2)return`<div class="screen-titlebar"><div><h2>Preview Source Data</h2><p>${esc(p.fileName)} · showing the first ${Math.min(15,p.rows.length)} of ${p.rows.length} rows exactly as read.</p></div></div><div class="source-scroll">${sourcePreviewHTML(p)}</div>`;if(p.step===3)return`<div class="screen-titlebar"><div><h2>Column Mapping</h2><p>Map at least one column to Name Surname. Unneeded columns can be ignored.</p></div></div><div style="max-width:760px">${mappingRowsHTML(p)}</div>`;if(p.step===4)return`<div class="screen-titlebar"><div><h2>Interpretation Preview</h2><p>Review exactly how each source row will become a guest record. Edit any incorrect value before continuing.</p></div></div><div class="source-scroll"><table class="preview-table interpret-table"><thead><tr><th>Source</th><th>Name Surname</th><th>Additional</th><th>Total Pax</th><th>Status</th><th>VIP</th><th>Table</th><th>Seat</th><th>Validation</th></tr></thead><tbody>${p.interpreted.map((r,i)=>interpretRowHTML(r,i)).join("")}</tbody></table></div>`;const s=importSummary(p.interpreted);return`<div class="screen-titlebar"><div><h2>Import Summary</h2><p>Final review. Existing data will not be replaced.</p></div></div><div class="wizard-summary"><div><span>Records</span><b>${s.records}</b></div><div><span>Total Guests</span><b>${s.guests}</b></div><div><span>Confirmed</span><b>${s.confirmed}</b></div><div><span>Tentative</span><b>${s.tentative}</b></div><div><span>Needs Attention</span><b>${s.attention}</b></div></div>${s.errors?`<div class="guide-tip guide-warning" style="margin-top:14px">${s.errors} row${s.errors===1?"":"s"} contain blocking errors. Go back to Interpretation and fix them before importing.</div>`:`<div class="guide-tip" style="margin-top:14px">Ready to import ${s.records} records representing ${s.guests} physical guests.</div>`}`}
  function wizardFootHTML(p){if(p.step===1)return`<button class="btn" data-wizard-close>Cancel</button>`;if(p.step===2)return`<button class="btn" data-wizard-back>Back</button><button class="btn primary" data-wizard-next>Continue to Mapping${icon("arrow")}</button>`;if(p.step===3)return`<button class="btn" data-wizard-back>Back</button><button class="btn primary" data-wizard-next>Interpret Rows${icon("arrow")}</button>`;if(p.step===4)return`<button class="btn" data-wizard-back>Back</button><button class="btn primary" data-wizard-next>Review Summary${icon("arrow")}</button>`;const s=importSummary(p.interpreted);return`<button class="btn" data-wizard-back>Back</button><button class="btn primary" data-wizard-import ${s.errors?"disabled":""}>Import Guests</button>`}
  function sourcePreviewHTML(p){return`<table class="preview-table"><thead><tr><th>#</th>${p.headers.map(h=>`<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>${p.rows.slice(0,15).map((row,i)=>`<tr><td>${i+1}</td>${p.headers.map(h=>`<td>${esc(row[h])}</td>`).join("")}</tr>`).join("")}</tbody></table>`}
  const MAP_FIELDS=[["","Ignore Column"],["name","Name Surname"],["pax","Total Pax"],["additionalGuests","Additional Guests"],["planningStatus","Status"],["vip","VIP Level"],["invitedBy","Invited By"],["notes","Notes"],["existingTable","Existing Table"],["existingSeat","Existing Seat"]];
  function mappingRowsHTML(p){return p.headers.map(h=>`<div class="mapping-grid"><div class="mapping-source" title="${esc(h)}">${esc(h)}</div><div class="mapping-arrow">→</div><select class="filter-input" data-map-header="${esc(h)}">${MAP_FIELDS.map(([v,l])=>`<option value="${v}" ${p.mapping[h]===v?"selected":""}>${l}</option>`).join("")}</select></div>`).join("")}
  function interpretRowHTML(r,i){const issues=r.issues||[];return`<tr><td title="${esc(r.sourceName)}">${esc(r.sourceName)}</td><td><input data-interp-row="${i}" data-interp-field="name" value="${esc(r.name)}"></td><td><input data-interp-row="${i}" data-interp-field="additionalGuests" type="number" min="0" value="${r.additionalGuests}"></td><td><b>${r.pax}</b></td><td><select data-interp-row="${i}" data-interp-field="planningStatus"><option ${r.planningStatus==="Confirmed"?"selected":""}>Confirmed</option><option ${r.planningStatus==="Tentative"?"selected":""}>Tentative</option></select></td><td><select data-interp-row="${i}" data-interp-field="vip">${["Standard","VIP","VVIP"].map(v=>`<option ${r.vip===v?"selected":""}>${v}</option>`).join("")}</select></td><td><input data-interp-row="${i}" data-interp-field="tableNumber" value="${esc(r.tableNumber||"")}"></td><td><input data-interp-row="${i}" data-interp-field="seatText" value="${esc(r.seatText||"")}"></td><td>${issues.length?issues.map(x=>`<div class="issue ${x.level}">⚠ ${esc(x.message)}</div>`).join(""):`<span style="color:#83b996">✓ Ready</span>`}</td></tr>`}
  function bindExcelWizard(){const p=pendingImport;document.querySelectorAll("[data-wizard-close]").forEach(b=>b.onclick=()=>{document.getElementById("excelDialog").close();pendingImport=null});const choose=document.querySelector("[data-wizard-choose]");if(choose)choose.onclick=()=>document.getElementById("guestFileInput").click();const template=document.querySelector("[data-wizard-template]");if(template)template.onclick=downloadExcelTemplate;const back=document.querySelector("[data-wizard-back]");if(back)back.onclick=()=>{p.step=Math.max(1,p.step-1);renderExcelWizard()};const next=document.querySelector("[data-wizard-next]");if(next)next.onclick=()=>{if(p.step===2){p.step=3}else if(p.step===3){document.querySelectorAll("[data-map-header]").forEach(s=>p.mapping[s.dataset.mapHeader]=s.value);if(!Object.values(p.mapping).includes("name")){toast("Map one column to Name Surname.","error");return}p.interpreted=interpretImportRows(p.rows,p.mapping,activeEvent());p.step=4}else if(p.step===4){revalidateInterpreted(p.interpreted,activeEvent());p.step=5}renderExcelWizard()};document.querySelectorAll("[data-interp-row]").forEach(el=>el.onchange=()=>{const r=p.interpreted[Number(el.dataset.interpRow)],field=el.dataset.interpField;r[field]=field==="additionalGuests"?Math.max(0,Number(el.value)||0):el.value;if(field==="additionalGuests"){r.pax=1+r.additionalGuests;r.issues=(r.issues||[]).filter(x=>!x.message.includes("Invalid additional guest")&&!x.message.includes("Invalid total pax"))}revalidateInterpreted(p.interpreted,activeEvent());renderExcelWizard()});const imp=document.querySelector("[data-wizard-import]");if(imp)imp.onclick=importInterpretedGuests}
  document.getElementById("guestFileInput").addEventListener("change",async e=>{const file=e.target.files[0];if(!file)return;try{let rows=[];if(file.name.toLowerCase().endsWith(".csv"))rows=parseCSV(await file.text());else{await loadXLSX();const data=await file.arrayBuffer(),book=XLSX.read(data,{type:"array"}),sheet=book.Sheets[book.SheetNames[0]];rows=XLSX.utils.sheet_to_json(sheet,{defval:"",raw:false})}if(!rows.length)throw new Error("The selected file contains no data rows.");pendingImport={step:2,fileName:file.name,rows,headers:Object.keys(rows[0]),mapping:autoMapping(Object.keys(rows[0])),interpreted:[]};if(!document.getElementById("excelDialog").open)document.getElementById("excelDialog").showModal();renderExcelWizard()}catch(err){console.error(err);toast(err.message||"Could not read this guest list.","error",5200)}e.target.value=""});
  function parseCSV(text){const lines=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++}else if(c==='"')quoted=!quoted;else if(c===","&&!quoted){row.push(cell);cell=""}else if((c==="\n"||c==="\r")&&!quoted){if(c==="\r"&&n==="\n")i++;row.push(cell);if(row.some(x=>x!==""))lines.push(row);row=[];cell=""}else cell+=c}row.push(cell);if(row.some(x=>x!==""))lines.push(row);if(lines.length<2)return[];const headers=lines[0].map((h,i)=>h.trim()||`Column ${i+1}`);return lines.slice(1).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??""])))}
  function loadXLSX(){return window.XLSX?Promise.resolve():Promise.reject(new Error("Embedded spreadsheet engine did not initialize."))}
  function norm(v){return String(v).toLowerCase().replace(/[^a-z0-9ğüşöçı]+/g,"")}
  function autoMapping(headers){const aliases={name:["name","namesurname","guestname","fullname","guest","misafir","adsoyad","isim"],pax:["pax","totalpax","totalguests","guests","kisi","kişi","adet"],additionalGuests:["additionalguests","additional","plus","ekmisafir","refakatci"],planningStatus:["status","planningstatus","durum"],vip:["vip","viplevel","level"],invitedBy:["invitedby","marketing","host","daveteden"],notes:["notes","note","not","aciklama","açıklama"],existingTable:["table","tablenumber","masa"],existingSeat:["seat","seats","koltuk"]},map={};headers.forEach(h=>{const n=norm(h);for(const[field,list]of Object.entries(aliases))if(list.some(a=>norm(a)===n)){map[h]=field;break}});return map}
  function mappedValue(row,mapping,field){const key=Object.keys(mapping).find(k=>mapping[k]===field);return key===undefined?"":row[key]}
  function parsePlanningStatus(value){const n=norm(value);if(["confirmed","kesin","definite","yes"].includes(n))return{value:"Confirmed",known:true};if(["tentative","belirsiz","uncertain","maybe"].includes(n))return{value:"Tentative",known:true};if(!n)return{value:"Confirmed",known:true};return{value:"Tentative",known:false}}
  function parseVip(value){const n=String(value||"").trim().toUpperCase();return["VIP","VVIP"].includes(n)?n:"Standard"}
  function parseSeatText(value){const out=[],re=/S?\s*(\d+)(?:\s*[-–]\s*S?\s*(\d+))?/gi,text=String(value||"");let m;while((m=re.exec(text))){const first=Number(m[1]),last=m[2]?Number(m[2]):first,step=last>=first?1:-1;if(Math.abs(last-first)>98){out.push(first-1);continue}for(let n=first;n!==last+step;n+=step)out.push(n-1)}return out}
  function interpretImportRows(rows,mapping,event){const interpreted=rows.map((row,index)=>{const sourceName=String(mappedValue(row,mapping,"name")||"").trim(),compact=parseCompactName(sourceName),addRaw=mappedValue(row,mapping,"additionalGuests"),paxRaw=mappedValue(row,mapping,"pax"),status=parsePlanningStatus(mappedValue(row,mapping,"planningStatus"));let additional=compact.additionalGuests,issues=[];if(String(addRaw).trim()!==""){const n=Number(addRaw);if(!Number.isInteger(n)||n<0)issues.push({level:"error",message:"Invalid additional guest number."});else additional=n}else if(String(paxRaw).trim()!==""){const n=Number(paxRaw);if(!Number.isInteger(n)||n<1)issues.push({level:"error",message:"Invalid total pax."});else additional=n-1}if(compact.detected&&String(addRaw).trim()!==""&&Number(addRaw)!==compact.additionalGuests)issues.push({level:"warn",message:"+N differs from Additional Guests; mapped column is used."});if(!status.known)issues.push({level:"warn",message:"Unknown status changed to Tentative."});return{sourceIndex:index,sourceName,name:compact.name,additionalGuests:Math.max(0,Number(additional)||0),pax:1+Math.max(0,Number(additional)||0),planningStatus:status.value,vip:parseVip(mappedValue(row,mapping,"vip")),invitedBy:String(mappedValue(row,mapping,"invitedBy")||"").trim(),notes:String(mappedValue(row,mapping,"notes")||"").trim(),tableNumber:String(mappedValue(row,mapping,"existingTable")||"").trim().toUpperCase(),seatText:String(mappedValue(row,mapping,"existingSeat")||"").trim(),issues}});revalidateInterpreted(interpreted,event);return interpreted}
  function revalidateInterpreted(rows,event){const counts=new Map(),pendingSeats=new Map();rows.forEach(r=>counts.set(norm(r.name),(counts.get(norm(r.name))||0)+1));rows.forEach(r=>{const preserved=(r.issues||[]).filter(x=>x.message.includes("mapped column")||x.message.includes("Unknown status")||x.message.includes("Invalid additional guest")||x.message.includes("Invalid total pax"));r.issues=preserved;r.additionalGuests=Math.max(0,Number(r.additionalGuests)||0);r.pax=1+r.additionalGuests;if(!String(r.name).trim())r.issues.push({level:"error",message:"Name is empty."});const key=norm(r.name);if(key&&(counts.get(key)>1||event.guests.some(g=>norm(g.name)===key)))r.issues.push({level:"warn",message:"Possible duplicate name."});if(r.tableNumber){const t=event.tables.find(x=>x.number.toUpperCase()===r.tableNumber.toUpperCase());if(!t){r.issues.push({level:"error",message:"Table number does not exist."});return}const seats=parseSeatText(r.seatText),used=occupiedSeatIndexes(event,t.id),pending=pendingSeats.get(t.id)||new Set();pendingSeats.set(t.id,pending);if(seats.length){const chosen=seats.slice(0,r.pax);if(seats.some(s=>s<0||s>=t.capacity))r.issues.push({level:"error",message:"Seat number is outside table capacity."});if(seats.length<r.pax)r.issues.push({level:"error",message:"Not enough seat numbers for total pax."});if(new Set(chosen).size<chosen.length)r.issues.push({level:"error",message:"The same seat number is listed more than once."});if(chosen.some(s=>used.has(s)||pending.has(s)))r.issues.push({level:"error",message:"One or more seats are already assigned."});if(!r.issues.some(x=>x.level==="error"))chosen.forEach(s=>pending.add(s))}else{const free=Array.from({length:t.capacity},(_,i)=>i).filter(i=>!used.has(i)&&!pending.has(i));if(free.length<r.pax)r.issues.push({level:"error",message:"Table does not have enough available seats."});else free.slice(0,r.pax).forEach(s=>pending.add(s))}}})}
  function importSummary(rows){return{records:rows.length,guests:rows.reduce((n,r)=>n+r.pax,0),confirmed:rows.filter(r=>r.planningStatus==="Confirmed").length,tentative:rows.filter(r=>r.planningStatus==="Tentative").length,attention:rows.filter(r=>r.issues?.length).length,errors:rows.filter(r=>r.issues?.some(x=>x.level==="error")).length}}
  function importInterpretedGuests(){const p=pendingImport,event=activeEvent(),summary=importSummary(p.interpreted);if(summary.errors){toast("Fix blocking import errors first.","error");return}let assigned=0;p.interpreted.forEach(r=>{const g={id:uid("guest"),name:String(r.name).trim(),additionalGuests:r.additionalGuests,pax:r.pax,planningStatus:r.planningStatus,vip:r.vip,invitedBy:r.invitedBy,notes:r.notes,arrivalStatus:"Not Arrived",assignment:null,createdAt:nowISO()};if(r.tableNumber){const t=event.tables.find(x=>x.number.toUpperCase()===r.tableNumber.toUpperCase()),used=occupiedSeatIndexes(event,t.id);let seats=parseSeatText(r.seatText);if(!seats.length)seats=Array.from({length:t.capacity},(_,i)=>i).filter(i=>!used.has(i)).slice(0,g.pax);if(seats.length>=g.pax&&!seats.slice(0,g.pax).some(i=>used.has(i))){g.assignment={tableId:t.id,seats:seats.slice(0,g.pax),locked:false};assigned++}}event.guests.push(g)});touchEvent(event);document.getElementById("excelDialog").close();pendingImport=null;render();toast(`${summary.records} guest records imported${assigned?` · ${assigned} assigned`:""}.`,"success",5000)}
  async function downloadExcelTemplate(){try{await loadXLSX();const rows=[["NAME SURNAME","ADDITIONAL GUESTS","STATUS","VIP","INVITED BY","NOTES"],["KEREM SARICICEK",3,"Confirmed","VIP","KEREM","Example: primary guest + 3"],["JOHN SMITH",0,"Tentative","Standard","MARKETING","Example single guest"],["KEREM SARICICEK +3","","Confirmed","VIP","KEREM","Compact +N notation is supported"]],ws=XLSX.utils.aoa_to_sheet(rows);ws["!cols"]=[{wch:28},{wch:20},{wch:14},{wch:12},{wch:18},{wch:36}];for(let c=0;c<6;c++){const cell=ws[XLSX.utils.encode_cell({r:0,c})];cell.s={font:{bold:true,color:{rgb:"FFFFFF"}},fill:{fgColor:{rgb:"2D3640"}},alignment:{horizontal:"center"},border:{bottom:{style:"medium",color:{rgb:"1F2428"}}}}}const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"GUEST TEMPLATE");XLSX.writeFile(wb,"merit-event-maker-guest-template.xlsx");toast("Excel template downloaded.","success")}catch(err){toast(err.message||"Excel template could not be created.","error",5200)}}

  function seatingHTML(event){const q=ui.seatingQuery.trim().toLocaleLowerCase("tr"),showAll=ui.seatingGuestScope==="all",records=event.guests.filter(g=>(showAll||!g.assignment)&&(!q||[g.name,g.vip,g.invitedBy,g.planningStatus,event.tables.find(t=>t.id===g.assignment?.tableId)?.number].join(" ").toLocaleLowerCase("tr").includes(q))),selected=event.guests.find(g=>g.id===ui.selectedGuestId),left=ui.leftCollapsed?collapsedPanel("left"):`<aside class="side-panel left"><div class="panel-head"><strong>${showAll?"All Guest Records":"Guests Needing Assignment"}</strong><button class="panel-toggle" data-panel-toggle="left">${icon("chevron")}</button></div>${selected?`<div class="selected-guest-banner"><b>${esc(selected.name)}${additionalOf(selected)?` +${additionalOf(selected)}`:""} · ${paxOf(selected)} pax</b>${selected.assignment?"Choose another table to move this guest record":"Ready to assign"}</div>`:""}<div class="guest-scope-strip">${[["all","All Guests"],["unassigned","Unassigned"]].map(([v,l])=>`<button class="seg-btn ${ui.seatingGuestScope===v?"active":""}" data-seating-scope="${v}">${l}</button>`).join("")}</div><div class="guest-filter-strip">${[["all","All Tables"],["empty","Empty Tables"],["available","Available Seats"],["full","Full Tables"]].map(([v,l])=>`<button class="seg-btn ${ui.seatingFilter===v?"active":""}" data-seating-filter="${v}">${l}</button>`).join("")}</div><div class="unassigned-search"><input class="filter-input" id="seatingSearch" value="${esc(ui.seatingQuery)}" placeholder="${showAll?"Search all guest records":"Search unassigned guests"}"></div><div class="unassigned-list">${records.length?records.map(g=>{const table=g.assignment&&event.tables.find(t=>t.id===g.assignment.tableId);return`<div class="guest-row-card ${ui.selectedGuestId===g.id?"selected":""}" draggable="true" data-seating-guest="${g.id}"><strong>${esc(g.name)}${additionalOf(g)?` +${additionalOf(g)}`:""}</strong><span><em>${esc(g.planningStatus)} · ${esc(g.vip)}</em><em>${table?esc(table.number):paxOf(g)+" pax"}</em></span></div>`}).join(""):`<div class="inspector-empty">${q?"No matching guest records.":showAll?"No guest records.":"Every guest is assigned."}</div>`}</div></aside>`;return`<div class="${editorClasses(true)}">${left}<section class="canvas-column">${canvasToolbarHTML(true)}${canvasViewportHTML(event,true)}</section>${selectedTablePanelHTML(event)}</div>`}
  function tableSeatMap(event,tableId){const map=new Map();event.guests.filter(g=>g.assignment?.tableId===tableId).forEach(g=>{g.assignment.seats.forEach((seat,i)=>map.set(seat,{guest:g,companion:i>0,index:i}))});return map}
  function selectedTablePanelHTML(event){if(ui.rightCollapsed)return collapsedPanel("right");const t=event.tables.find(x=>x.id===ui.selectedTableId);if(!t)return`<aside class="side-panel right"><div class="panel-head"><strong>Selected Table</strong><button class="panel-toggle" data-panel-toggle="right">${icon("chevron")}</button></div><div class="inspector-empty">Select a table to review capacity, occupied seats and guest names.</div></aside>`;const map=tableSeatMap(event,t.id),occupied=tableAssignedPax(event,t.id),empty=Math.max(0,t.capacity-occupied),selected=event.guests.find(g=>g.id===ui.selectedGuestId);return`<aside class="side-panel right"><div class="panel-head"><strong>Selected Table</strong><button class="panel-toggle" data-panel-toggle="right">${icon("chevron")}</button></div><div class="table-summary"><h3>${esc(formatTableNumber(t.number))}</h3><div class="occupancy-strip"><div class="occupancy-stat"><span>Capacity</span><b>${t.capacity}</b></div><div class="occupancy-stat"><span>Occupied</span><b>${occupied}</b></div><div class="occupancy-stat"><span>Empty</span><b>${empty}</b></div></div>${selected?`<button class="btn primary sm" style="width:100%;margin-top:10px" data-assign-selected="${t.id}">${selected.assignment&&selected.assignment.tableId!==t.id?"Move":"Assign"} ${esc(selected.name)} (${paxOf(selected)} seats)</button>`:`<div class="dialog-note" style="margin-top:9px">Select a guest on the left, then assign the required number of seats.</div>`}</div><div class="seat-list">${Array.from({length:t.capacity},(_,i)=>seatRowHTML(i,map.get(i),selected)).join("")}</div></aside>`}
  function seatRowHTML(index,occupant,selected){if(!occupant)return`<div class="seat-row empty" data-empty-seat="${index}"><span class="seat-no">S${index+1}</span><span class="seat-person">Empty</span>${selected?"<button class='seat-action'>Assign here</button>":"<span></span>"}</div>`;const g=occupant.guest,label=occupant.companion?`GUEST OF ${g.name.toUpperCase()}`:g.name;return`<div class="seat-row"><span class="seat-no">S${index+1}</span><span class="seat-person">${esc(label)} ${occupant.companion?"<small>companion</small>":""}</span>${occupant.index===0?`<span><button class="seat-action" data-lock-assignment="${g.id}">${g.assignment.locked?"Unlock":"Lock"}</button> <button class="seat-action" data-unassign="${g.id}">Unassign</button></span>`:"<span></span>"}</div>`}
  function bindSeating(){bindPanelToggles();const search=document.getElementById("seatingSearch");if(search)search.oninput=()=>{ui.seatingQuery=search.value;const p=search.selectionStart;render();requestAnimationFrame(()=>{const n=document.getElementById("seatingSearch");n?.focus();n?.setSelectionRange(p,p)})};app.querySelectorAll("[data-seating-scope]").forEach(b=>b.onclick=()=>{ui.seatingGuestScope=b.dataset.seatingScope;ui.selectedGuestId=null;render()});app.querySelectorAll("[data-seating-filter]").forEach(b=>b.onclick=()=>{ui.seatingFilter=b.dataset.seatingFilter;render()});app.querySelectorAll("[data-seating-guest]").forEach(row=>{row.onclick=()=>{ui.selectedGuestId=row.dataset.seatingGuest;render()};row.ondragstart=e=>e.dataTransfer.setData("application/x-merit-guest",row.dataset.seatingGuest)});const assign=app.querySelector("[data-assign-selected]");if(assign)assign.onclick=()=>assignGuestToTable(ui.selectedGuestId,assign.dataset.assignSelected);app.querySelectorAll("[data-empty-seat]").forEach(row=>row.onclick=()=>{if(ui.selectedGuestId)assignGuestToTable(ui.selectedGuestId,ui.selectedTableId,Number(row.dataset.emptySeat))});app.querySelectorAll("[data-unassign]").forEach(b=>b.onclick=()=>unassignGuest(b.dataset.unassign));app.querySelectorAll("[data-lock-assignment]").forEach(b=>b.onclick=()=>toggleAssignmentLock(b.dataset.lockAssignment))}
  function assignGuestToTable(guestId,tableId,preferred=null){const event=activeEvent(),g=event.guests.find(x=>x.id===guestId),t=event.tables.find(x=>x.id===tableId);if(!g||!t)return;const moving=!!g.assignment&&g.assignment.tableId!==tableId;if(g.assignment?.locked){toast(`${g.name}'s assignment is locked. Unlock it before moving.`,"error");return}const used=occupiedSeatIndexes(event,tableId,g.id),free=Array.from({length:t.capacity},(_,i)=>i).filter(i=>!used.has(i));if(free.length<paxOf(g)){toast(`${t.number} has only ${free.length} available seats. ${g.name} requires ${paxOf(g)}.`,"error",5000);return}let seats=[];if(preferred!==null&&free.includes(preferred)){seats=[preferred,...free.filter(i=>i!==preferred).slice(0,paxOf(g)-1)]}else seats=free.slice(0,paxOf(g));g.assignment={tableId,seats,locked:false};ui.selectedTableId=tableId;ui.highlightId=tableId;touchEvent(event);render();toast(`${g.name} ${moving?"moved to":"assigned to"} ${t.number} · ${paxOf(g)} seats reserved.`,"success")}
  function unassignGuest(id){const event=activeEvent(),g=event.guests.find(x=>x.id===id);if(!g?.assignment)return;if(g.assignment.locked){toast("Unlock this assignment before removing it.","error");return}g.assignment=null;ui.selectedGuestId=id;touchEvent(event);render();toast(`${g.name} returned to Unassigned.`)}
  function toggleAssignmentLock(id){const event=activeEvent(),g=event.guests.find(x=>x.id===id);if(!g?.assignment)return;g.assignment.locked=!g.assignment.locked;touchEvent(event);render();toast(g.assignment.locked?"Assignment locked.":"Assignment unlocked.")}

  function liveHTML(event){const q=ui.liveQuery.trim().toLocaleLowerCase("tr"),rows=event.guests.filter(g=>!q||[g.name,g.vip,g.invitedBy,g.planningStatus,g.arrivalStatus].join(" ").toLocaleLowerCase("tr").includes(q)),m=eventMetrics(event),s=seatingStats(event),checked=event.guests.filter(g=>g.arrivalStatus==="Checked In").reduce((n,g)=>n+paxOf(g),0),notArrived=event.guests.filter(g=>g.arrivalStatus==="Not Arrived").reduce((n,g)=>n+paxOf(g),0),noShow=event.guests.filter(g=>g.arrivalStatus==="No Show").reduce((n,g)=>n+paxOf(g),0);return`<div class="screen-scroll"><div class="screen-inner"><div class="screen-titlebar"><div><h2>Live Event</h2><p>Operational seating vacancy and arrival control.</p></div><input class="filter-input" id="liveSearch" value="${esc(ui.liveQuery)}" placeholder="Search arriving guest"></div><div class="live-kpis"><button class="live-kpi" data-live-kpi="all"><span class="kpi-top">Total Guests${icon("users")}</span><b>${m.guests}</b><small>Open Seating with all guest records</small></button><button class="live-kpi" data-live-kpi="empty"><span class="kpi-top">Empty Tables${icon("table")}</span><b>${s.emptyTables}</b><small>Tables with zero assigned guests</small></button><button class="live-kpi" data-live-kpi="available"><span class="kpi-top">Empty Chairs${icon("chair")}</span><b>${s.emptyChairs}</b><small>Available physical seats across modeled tables</small></button></div><div class="arrival-summary"><span>Not Arrived <b>${notArrived}</b></span><span>Checked In <b>${checked}</b></span><span>No Show <b>${noShow}</b></span></div><div class="live-list"><div class="live-row header"><span>Name Surname</span><span>Pax</span><span>Table</span><span>Planning</span><span>Arrival</span><span>Action</span></div>${rows.map(g=>{const t=g.assignment&&event.tables.find(x=>x.id===g.assignment.tableId);return`<div class="live-row"><span><b>${esc(g.name)}${additionalOf(g)?` +${additionalOf(g)}`:""}</b><small class="subline">${esc(g.vip)}</small></span><span>${paxOf(g)}</span><span>${t?esc(t.number):"—"}</span><span>${esc(g.planningStatus)}</span><span class="${g.arrivalStatus==="Checked In"?"arrival-checked":g.arrivalStatus==="No Show"?"arrival-no-show":""}">${esc(g.arrivalStatus)}</span><span class="live-actions"><button class="btn sm ${g.arrivalStatus==="Checked In"?"active":""}" data-arrival="Checked In" data-live-guest="${g.id}">Check In</button><button class="btn sm ${g.arrivalStatus==="No Show"?"danger":""}" data-arrival="No Show" data-live-guest="${g.id}">No Show</button></span></div>`}).join("")}</div></div></div>`}
  function bindLive(){const search=document.getElementById("liveSearch");search.oninput=()=>{ui.liveQuery=search.value;const p=search.selectionStart;render();requestAnimationFrame(()=>{const n=document.getElementById("liveSearch");n?.focus();n?.setSelectionRange(p,p)})};app.querySelectorAll("[data-live-kpi]").forEach(b=>b.onclick=()=>{const target=b.dataset.liveKpi;ui.tab="seating";ui.seatingFilter=target;ui.seatingGuestScope=target==="all"?"all":"unassigned";ui.seatingQuery="";ui.selectedGuestId=null;ui.selectedTableId=null;render()});app.querySelectorAll("[data-live-guest]").forEach(b=>b.onclick=()=>{const event=activeEvent(),g=event.guests.find(x=>x.id===b.dataset.liveGuest),status=b.dataset.arrival;g.arrivalStatus=g.arrivalStatus===status?"Not Arrived":status;touchEvent(event);render();toast(`${g.name}: ${g.arrivalStatus}.`,"success")})}

  function reportsHTML(event){const m=eventMetrics(event),s=seatingStats(event),alphabetical=[...event.guests].sort((a,b)=>naturalSort(a.name,b.name)),unassigned=alphabetical.filter(g=>!g.assignment),pax=t("unit.pax");return`<div class="screen-scroll"><div class="screen-inner"><div class="screen-titlebar"><div><h2>${t("reports.title")}</h2><p>${t("reports.subtitle")}</p></div><div class="toolbar-row"><button class="btn" data-report="csv">${icon("download")}${t("reports.guestCsv")}</button><button class="btn primary" data-report="xlsx">${icon("download")}${t("reports.exportTablePlan")}</button></div></div><div class="reports-grid"><section class="report-panel"><div class="report-head"><h3>${t("reports.capacitySummary")}</h3><span class="muted">${t("reports.live")}</span></div><div class="report-body">${reportRow(t("reports.totalCapacity"),m.total)}${reportRow(t("reports.assignedGuests"),m.assigned)}${reportRow(t("reports.emptyChairs"),s.emptyChairs)}${reportRow(t("reports.emptyTables"),s.emptyTables)}</div></section><section class="report-panel"><div class="report-head"><h3>${t("reports.tableList")}</h3><span class="muted">${t("reports.tablesCount",{n:event.tables.length})}</span></div><div class="report-body">${[...event.tables].sort((a,b)=>naturalSort(a.number,b.number)).map(t_=>reportRow(`${esc(t_.number)} · ${esc(t_.zone)}`,`${tableAssignedPax(event,t_.id)} / ${t_.capacity}`)).join("")}</div></section><section class="report-panel wide"><div class="report-head"><h3>${t("reports.alphabeticalGuestList")}</h3><span class="muted">${t("reports.recordsCount",{n:event.guests.length})}</span></div><div class="report-body">${alphabetical.map(g=>{const t_=g.assignment&&event.tables.find(x=>x.id===g.assignment.tableId);return reportRow(`${esc(g.name)}${additionalOf(g)?` +${additionalOf(g)}`:""} · ${paxOf(g)} ${pax} · ${esc(t("status.planning."+g.planningStatus))}`,t_?`${esc(t_.number)} / ${seatRange(g.assignment.seats)}`:t("reports.unassigned"))}).join("")}</div></section><section class="report-panel wide"><div class="report-head"><h3>${t("reports.unassigned")}</h3><span class="muted">${t("reports.guestsCount",{n:unassigned.reduce((n,g)=>n+paxOf(g),0)})}</span></div><div class="report-body">${unassigned.length?unassigned.map(g=>reportRow(`${esc(g.name)} · ${paxOf(g)} ${pax}`,esc(g.invitedBy||"—"))).join(""):reportRow(t("reports.allAssigned"),t("reports.ready"))}</div></section></div></div></div>`}
  function reportRow(a,b){return`<div class="report-row"><span>${a}</span><span>${b}</span></div>`}
  function bindReports(){app.querySelector("[data-report='csv']").onclick=exportGuestCSV;app.querySelector("[data-report='xlsx']").onclick=exportTablePlanXLSX}
  function exportGuestCSV(){const event=activeEvent(),headers=["NAME SURNAME","PAX","STATUS","VIP","INVITED BY","TABLE","SEATS","NOTES"],rows=event.guests.map(g=>{const t=g.assignment&&event.tables.find(x=>x.id===g.assignment.tableId);return[g.name,paxOf(g),g.planningStatus,g.vip,g.invitedBy,t?.number||"",g.assignment?seatRange(g.assignment.seats):"",g.notes]}),csv="﻿"+[headers,...rows].map(r=>r.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(",")).join("\r\n"),blob=new Blob([csv],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=safeFileName(event.name)+"-guests.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast("Guest CSV exported.","success")}
  function safeFileName(value){return String(value).toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"event"}
  function seatExportName(event,table,index){const occ=tableSeatMap(event,table.id).get(index);if(!occ)return"";return occ.companion?`GUEST OF ${occ.guest.name.toUpperCase()}`:occ.guest.name.toUpperCase()}
  function buildTablePlanModel(event){const tables=[...event.tables].sort((a,b)=>naturalTableSort(a.number,b.number)),aoa=[],merges=[],cards=[];let startRow=0;for(let g=0;g<tables.length;g+=4){const group=tables.slice(g,g+4),maxSeats=Math.max(...group.map(t=>t.capacity));group.forEach((t,j)=>{const c=j*3;aoa[startRow]??=[];aoa[startRow][c]=formatTableNumber(t.number);aoa[startRow][c+1]="";merges.push({s:{r:startRow,c},e:{r:startRow,c:c+1}});for(let s=0;s<t.capacity;s++){aoa[startRow+1+s]??=[];aoa[startRow+1+s][c]="S"+(s+1);aoa[startRow+1+s][c+1]=seatExportName(event,t,s)}const totalRow=startRow+1+t.capacity;aoa[totalRow]??=[];aoa[totalRow][c]="TOTAL GUEST:";aoa[totalRow][c+1]=tableAssignedPax(event,t.id);cards.push({table:t,startRow,col:c,totalRow})});startRow+=maxSeats+4}return{tables,aoa,merges,cards,lastRow:Math.max(0,startRow-2)}}
  function borderStyle(style="thin"){const c={rgb:"34383C"};return{top:{style,color:c},bottom:{style,color:c},left:{style,color:c},right:{style,color:c}}}
  function makeTablePlanSheet(event){const model=buildTablePlanModel(event),ws=XLSX.utils.aoa_to_sheet(model.aoa);ws["!merges"]=model.merges;ws["!cols"]=[{wch:8},{wch:28},{wch:3},{wch:8},{wch:28},{wch:3},{wch:8},{wch:28},{wch:3},{wch:8},{wch:28}];ws["!rows"]=Array.from({length:model.lastRow+1},()=>({hpt:18}));model.cards.forEach(card=>{const{table,startRow,col,totalRow}=card,headStyle={font:{bold:true,sz:12,color:{rgb:"202428"}},fill:{fgColor:{rgb:"F0CF58"}},alignment:{horizontal:"center",vertical:"center"},border:borderStyle("medium")},head=ws[XLSX.utils.encode_cell({r:startRow,c:col})],headEnd=ws[XLSX.utils.encode_cell({r:startRow,c:col+1})];head.s=clone(headStyle);headEnd.s=clone(headStyle);ws["!rows"][startRow]={hpt:23};for(let i=0;i<table.capacity;i++){const left=ws[XLSX.utils.encode_cell({r:startRow+1+i,c:col})],right=ws[XLSX.utils.encode_cell({r:startRow+1+i,c:col+1})];left.s={font:{bold:true,color:{rgb:"30363B"}},fill:{fgColor:{rgb:"C9CDD1"}},alignment:{horizontal:"center",vertical:"center"},border:borderStyle()};right.s={fill:{fgColor:{rgb:"E3E5E7"}},alignment:{horizontal:"left",vertical:"center"},border:borderStyle()}}const label=ws[XLSX.utils.encode_cell({r:totalRow,c:col})],value=ws[XLSX.utils.encode_cell({r:totalRow,c:col+1})];label.s={font:{bold:true},fill:{fgColor:{rgb:"C3C7CA"}},alignment:{horizontal:"right"},border:borderStyle("medium")};value.s={font:{bold:true},fill:{fgColor:{rgb:"C3C7CA"}},alignment:{horizontal:"center"},border:borderStyle("medium")}});ws["!pageSetup"]={orientation:"landscape",fitToWidth:1,fitToHeight:0};ws["!margins"]={left:.25,right:.25,top:.4,bottom:.4,header:.2,footer:.2};ws["!printArea"]=`A1:K${model.lastRow+1}`;return ws}
  function makeListSheet(event,onlyUnassigned=false){const source=[...event.guests].filter(g=>!onlyUnassigned||!g.assignment).sort((a,b)=>naturalSort(a.name,b.name)),rows=[["NAME SURNAME","PAX","STATUS","VIP","INVITED BY","TABLE","SEATS","NOTES"],...source.map(g=>{const t=g.assignment&&event.tables.find(x=>x.id===g.assignment.tableId);return[g.name,paxOf(g),g.planningStatus,g.vip,g.invitedBy,t?.number||"",g.assignment?seatRange(g.assignment.seats):"",g.notes]})],ws=XLSX.utils.aoa_to_sheet(rows);ws["!cols"]=[{wch:28},{wch:8},{wch:14},{wch:10},{wch:20},{wch:10},{wch:16},{wch:36}];ws["!autofilter"]={ref:`A1:H${rows.length}`};ws["!freeze"]={xSplit:0,ySplit:1};for(let c=0;c<8;c++){const cell=ws[XLSX.utils.encode_cell({r:0,c})];cell.s={font:{bold:true,color:{rgb:"FFFFFF"}},fill:{fgColor:{rgb:"2D3640"}},alignment:{horizontal:"center"},border:borderStyle("medium")}}for(let r=1;r<rows.length;r++)for(let c=0;c<8;c++){const cell=ws[XLSX.utils.encode_cell({r,c})];if(cell)cell.s={fill:{fgColor:{rgb:r%2?"F2F3F4":"E7E9EA"}},alignment:{vertical:"center",wrapText:c===7},border:borderStyle()}}return ws}
  async function exportTablePlanXLSX(){try{await loadXLSX();const event=activeEvent(),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,makeTablePlanSheet(event),"TABLE PLAN");XLSX.utils.book_append_sheet(wb,makeListSheet(event,false),"GUEST LIST");XLSX.utils.book_append_sheet(wb,makeListSheet(event,true),"UNASSIGNED");XLSX.writeFile(wb,safeFileName(event.name)+"-table-plan.xlsx",{cellStyles:true});toast("Table Plan workbook exported with three worksheets.","success",5000)}catch(err){console.error(err);toast(err.message||"The Table Plan workbook could not be created.","error",5200)}}

  const GUIDE_EN=[
    {id:"start",title:"Getting Started",intro:"Create an event and understand the operational workspace before editing data.",items:[
      ["Creating an Event","From All Events, select Create Event. Enter the event name, date, venue and event status, then select Create Event. A structured sample plan is included so every feature can be tested immediately."],
      ["Understanding the Event Workspace","Use Overview for readiness, Floor Plan for geometry, Guests for planning data, Seating for assignments, Live Event for arrivals, and Reports for operational exports. The compact strip always shows current capacity and assignment totals."]]},
    {id:"floor",title:"Floor Plan",intro:"Build the physical plan with explicit seat counts and a locked reference layer.",visual:"floor",items:[
      ["Importing a Floor Plan","Open Floor Plan → Plan → Reference → Import. Choose a PNG or JPG. The image becomes a reference layer below interactive objects; PDF is intentionally not supported in this standalone prototype."],
      ["Reference Layer Controls","Use On/Off, Locked/Unlocked, Opacity, Scale, Fit and Remove. Locking prevents accidental reference changes; tables placed above it remain independent objects."],
      ["Creating Each Table Type","Choose Rectangle, Square, Round or Bistro from Build → Tables. Rectangle suits long seating, Square compact groups, Round circular arrangements, and Bistro smaller modeled seating."],
      ["Selecting Seat Count","Selecting a table type opens a creation panel first. Choose a preset or enter any custom positive seat count, confirm the number and zone, then select Add to Plan."],
      ["Changing Seat Count","Select a table. In Inspector → Seating, use minus, plus, presets or Custom. Chairs, capacity and vacancy totals update immediately. A table cannot be reduced below occupied pax."],
      ["Moving, Resizing and Rotating","With Select active, drag the object to move it. Use the square handle to resize and the circular handle to rotate. Snap aligns movement and rotation; Pan moves the canvas view."],
      ["Table Numbering","New tables receive the next T or B number. Edit Table Number in the Inspector for custom codes. Duplicate numbers are rejected so reports remain unambiguous."],
      ["Seat Numbering","Enable Seat labels in the canvas toolbar. User-facing labels are S1, S2, S3 and continue to the table capacity. Seat labels are also used in Seating and Excel export."],
      ["Zones","Assign VIP FRONT, VIP, MAIN FLOOR, BISTRO or RESERVED in the Inspector. Zones organize operations without covering the plan in decorative colors."]]},
    {id:"guests",title:"Guests & Excel Import",intro:"One record can reserve several physical seats without creating separate unnamed records.",visual:"excel",items:[
      ["Importing Excel","Guests → Import Excel opens a five-step process: choose file, source preview, mapping, interpretation and summary. No row is imported before the final confirmation."],
      ["Correct Excel Format","Recommended columns are NAME SURNAME, ADDITIONAL GUESTS, STATUS, VIP, INVITED BY and NOTES. Use the downloadable template to avoid mapping errors."],
      ["Meaning of Additional Guests","Additional Guests excludes the primary person. A value of 3 means one named guest plus three companions, therefore Total Pax is 4."],
      ["How KEREM SARICICEK +3 Works","The parser accepts +3, + 3 and mixed capitalization. It stores KEREM SARICICEK as the name, 3 as Additional Guests and 4 as Total Pax."],
      ["Column Mapping","Match each source column to Name Surname, Total Pax, Additional Guests, Status, VIP, Invited By, Notes, Existing Table or Existing Seat. Choose Ignore Column for irrelevant data."],
      ["Import Preview","Source Preview shows the file exactly as read. Interpretation Preview shows the cleaned name, companion count, pax, status and assignment fields. Edit incorrect values before Summary."],
      ["Confirmed vs Tentative","Confirmed means attendance is considered definite. Tentative means attendance is not certain. These planning statuses never change when a guest is checked in or marked No Show."],
      ["Adding a Guest Manually","Select Add Guest, enter Name Surname and Additional Guests, verify the live Total Pax, choose Confirmed or Tentative, then complete VIP, Invited By and Notes."]]},
    {id:"seating",title:"Seating",intro:"Reserve real seats, move complete multi-pax records and inspect vacancy in one mode.",visual:"seating",items:[
      ["Seating Mode","The floor geometry is protected in Seating. The left panel lists guests needing assignment, the center shows the plan, and the right panel shows the selected table and every seat."],
      ["Assigning a Guest","Select a guest on the left, select a table, then use Assign. You can also drag the guest onto a table. The system checks physical vacancy before reserving seats."],
      ["Assigning +3 Guest Groups","KEREM SARICICEK +3 requires four free seats. The primary seat shows the name; the next three show GUEST OF KEREM SARICICEK. The record stays unified."],
      ["Moving a Guest","Select an already assigned guest through search, then select another table and choose Move. The old seats are released only after the destination passes the capacity check."],
      ["Unassigning","Select the table and use Unassign next to the primary guest seat. Locked assignments must be unlocked first. All seats reserved by that record are released together."],
      ["Seat-specific Assignment","After selecting a guest, choose Assign here on an empty seat. That becomes the first reserved seat; remaining required seats use the next available positions."],
      ["Empty Tables","Choose Empty Tables or click the Live Event KPI. Tables with zero assigned pax remain emphasized while surrounding context is dimmed. Clear the filter from the banner."],
      ["Empty Chairs","Choose Available Seats or click Empty Chairs in Live Event. The count equals capacity minus occupied physical seats across every modeled seated table, including modeled Bistro seats."]]},
    {id:"live",title:"Live Event & Export",intro:"Arrival tracking stays separate from planning certainty and links directly to seating operations.",visual:"workbook",items:[
      ["Live Event Mode","The three operational KPIs are Total Guests, Empty Tables and Empty Chairs. Each is clickable and opens Seating with the relevant context or filter."],
      ["Check-in","Use Check In or No Show on the arrival list. The arrival state changes between Not Arrived, Checked In and No Show without changing Confirmed or Tentative."],
      ["Excel Export","Reports → Export Table Plan creates a real .xlsx workbook. Internet access is required once to load the embedded Excel engine used by this standalone file."],
      ["Understanding the Table Plan Workbook","TABLE PLAN contains four table cards per horizontal group. GUEST LIST contains all records. UNASSIGNED contains only records without a table. Companion seats are exported as GUEST OF [PRIMARY NAME]."]]},
    {id:"operations",title:"Everyday Operations & Troubleshooting",intro:"Use search, history and local safeguards to keep the event plan controlled.",items:[
      ["Search","The top search finds names, inviters, tables and seats. Selecting a result opens Seating, selects the assigned table and highlights it. Guest and Live Event screens also have focused search."],
      ["Undo / Redo","Floor Plan Undo and Redo cover table, venue and reference-layer edits. Keyboard shortcuts Ctrl/Cmd+Z and Ctrl/Cmd+Y work when you are not typing in a field."],
      ["Local Storage Limitations","Data is saved only in this browser profile. Clearing browser data, changing devices or using private mode can remove it. Export the workbook regularly; very large reference images may not persist."],
      ["Common Mistakes / Troubleshooting","If import fails, verify Name Surname mapping and fix red validation messages. If assignment fails, check available seats. If a table will not move, unlock it. If Excel buttons fail, check internet access and retry."]]},
  ];
  const GUIDE_TR=[
    {id:"start",title:"Başlangıç",intro:"Veri düzenlemeden önce etkinliği oluşturun ve operasyon çalışma alanını tanıyın.",items:[
      ["Etkinlik Oluşturma","Tüm Etkinlikler ekranında Create Event düğmesini seçin. Etkinlik adı, tarih, mekân ve etkinlik durumunu girip Create Event ile tamamlayın. Sistemi hemen deneyebilmeniz için düzenli bir örnek plan otomatik gelir."],
      ["Etkinlik Çalışma Alanını Anlama","Overview hazırlık durumunu, Floor Plan fiziksel düzeni, Guests planlama verilerini, Seating masa atamalarını, Live Event giriş durumlarını ve Reports operasyon çıktılarını yönetir. Üst şerit kapasite ve atama sayılarını sürekli güncel gösterir."]]},
    {id:"floor",title:"Salon Planı",intro:"Açık koltuk sayıları ve kilitli referans katmanıyla fiziksel yerleşimi kurun.",visual:"floor",items:[
      ["Salon Planı Yükleme","Floor Plan → Plan → Reference → Import yolunu izleyin ve PNG veya JPG seçin. Görsel, etkileşimli nesnelerin altında referans katmanı olur. Bu tek dosyalık prototipte PDF bilinçli olarak desteklenmez."],
      ["Referans Katmanı Kontrolleri","On/Off, Locked/Unlocked, Opacity, Scale, Fit ve Remove seçeneklerini kullanın. Kilit, referans görselini korur; üstündeki masalar bağımsız kalır."],
      ["Her Masa Türünü Oluşturma","Build → Tables altında Rectangle, Square, Round veya Bistro seçin. Rectangle uzun yerleşim, Square kompakt grup, Round dairesel düzen, Bistro ise küçük ve koltukları modellenmiş alan içindir."],
      ["Koltuk Sayısı Seçme","Masa türünü seçtiğiniz anda önce oluşturma paneli açılır. Hazır sayılardan birini seçin veya istediğiniz pozitif özel sayıyı girin; masa numarası ve bölgeyi kontrol edip Add to Plan seçin."],
      ["Koltuk Sayısını Değiştirme","Masayı seçin. Inspector → Seating bölümünde eksi, artı, hazır değerler veya Custom kullanın. Sandalyeler, kapasite ve boşluk sayıları hemen değişir. Dolu kişi sayısının altına inilemez."],
      ["Taşıma, Boyutlandırma ve Döndürme","Select açıkken nesneyi sürükleyerek taşıyın. Kare tutamaç boyutu, dairesel tutamaç açıyı değiştirir. Snap hizalama yapar; Pan tuvali hareket ettirir."],
      ["Masa Numaralandırma","Yeni masalara sıradaki T veya B numarası verilir. Özel kod için Inspector içindeki Table Number alanını değiştirin. Raporların karışmaması için aynı numaranın tekrarına izin verilmez."],
      ["Koltuk Numaralandırma","Tuval araç çubuğunda Seat labels seçeneğini açın. Görünen numaralar S1, S2, S3 biçimindedir ve masa kapasitesi kadar devam eder. Aynı numaralar Seating ve Excel çıktısında kullanılır."],
      ["Bölgeler","Inspector içinden VIP FRONT, VIP, MAIN FLOOR, BISTRO veya RESERVED seçin. Bölge bilgisi planı gereksiz renklere boğmadan operasyonu düzenler."]]},
    {id:"guests",title:"Misafirler ve Excel İçe Aktarma",intro:"Tek bir kayıt, isimsiz kişiler için ayrı kayıt açmadan birden fazla gerçek koltuğu ayırabilir.",visual:"excel",items:[
      ["Excel İçe Aktarma","Guests → Import Excel beş aşamalı süreci açar: dosya seçimi, kaynak önizleme, kolon eşleştirme, yorumlama ve özet. Son onay verilmeden hiçbir satır içe aktarılmaz."],
      ["Doğru Excel Formatı","Önerilen kolonlar NAME SURNAME, ADDITIONAL GUESTS, STATUS, VIP, INVITED BY ve NOTES biçimindedir. Eşleştirme hatalarını azaltmak için indirilebilir şablonu kullanın."],
      ["Additional Guests Anlamı","Additional Guests ana kişiyi içermez. Değer 3 ise bir isimli kişi ile üç refakatçi vardır; Total Pax 4 olur."],
      ["KEREM SARICICEK +3 Nasıl Çalışır","Ayrıştırıcı +3, + 3 ve farklı büyük-küçük harfleri kabul eder. İsim KEREM SARICICEK, Additional Guests 3 ve Total Pax 4 olarak saklanır."],
      ["Kolon Eşleştirme","Kaynak kolonları Name Surname, Total Pax, Additional Guests, Status, VIP, Invited By, Notes, Existing Table veya Existing Seat alanlarıyla eşleştirin. Gereksiz kolon için Ignore Column seçin."],
      ["İçe Aktarma Önizlemesi","Source Preview dosyayı okunduğu haliyle gösterir. Interpretation Preview temizlenen isim, refakatçi sayısı, toplam kişi, durum ve masa alanlarını gösterir. Yanlış değerleri Summary aşamasından önce düzeltin."],
      ["Confirmed ve Tentative","Confirmed katılımın kesin kabul edildiğini, Tentative ise henüz kesin olmadığını belirtir. Giriş yapıldı veya No Show oldu diye bu planlama durumu değişmez."],
      ["Elle Misafir Ekleme","Add Guest seçin; Name Surname ve Additional Guests alanlarını doldurun, anlık Total Pax sayısını kontrol edin, Confirmed veya Tentative seçip VIP, Invited By ve Notes bilgilerini tamamlayın."]]},
    {id:"seating",title:"Oturma Düzeni",intro:"Gerçek koltukları ayırın, çok kişili kayıtları bütün olarak taşıyın ve boşlukları tek ekranda görün.",visual:"seating",items:[
      ["Seating Modu","Seating ekranında fiziksel düzen korumaya alınır. Solda atama bekleyen misafirler, ortada plan, sağda seçilen masa ve bütün koltuklar bulunur."],
      ["Misafir Atama","Soldan misafiri, ardından masayı seçip Assign kullanın. Misafiri masaya sürüklemek de mümkündür. Sistem koltuk ayırmadan önce gerçek boşluğu kontrol eder."],
      ["+3 Kişilik Kayıt Atama","KEREM SARICICEK +3 için dört boş koltuk gerekir. İlk koltukta ana isim, sonraki üçünde GUEST OF KEREM SARICICEK görünür. Kayıt bölünmez."],
      ["Misafiri Başka Masaya Taşıma","Aramadan atanmış misafiri seçin, yeni masayı açıp Move kullanın. Eski koltuklar ancak hedef masanın kapasite kontrolü geçtikten sonra boşaltılır."],
      ["Atamayı Kaldırma","Masayı seçip ana misafir koltuğunun yanındaki Unassign seçeneğini kullanın. Kilitli atama önce açılmalıdır. O kaydın ayırdığı tüm koltuklar birlikte boşalır."],
      ["Belirli Koltuğa Atama","Misafiri seçtikten sonra boş bir koltukta Assign here kullanın. Bu koltuk ilk koltuk olur; gereken diğer yerler uygun boş koltuklardan tamamlanır."],
      ["Boş Masalar","Empty Tables filtresini veya Live Event içindeki KPI'yı seçin. Hiç atanmış kişisi olmayan masalar vurgulanır, çevre plan soluklaşır. Üstteki göstergeden filtreyi temizleyin."],
      ["Boş Koltuklar","Available Seats filtresini veya Live Event içindeki Empty Chairs değerini seçin. Sayı, koltukları modellenmiş bütün masalarda kapasite eksi dolu koltuk toplamıdır; koltuklu Bistro masaları buna dahildir."]]},
    {id:"live",title:"Canlı Etkinlik ve Dışa Aktarma",intro:"Giriş takibi planlama kesinliğinden ayrı kalır ve doğrudan oturma operasyonuna bağlanır.",visual:"workbook",items:[
      ["Live Event Modu","Üç operasyon göstergesi Total Guests, Empty Tables ve Empty Chairs değerleridir. Her biri tıklanabilir ve Seating ekranını uygun bağlam veya filtreyle açar."],
      ["Check-in","Giriş listesinde Check In veya No Show kullanın. Arrival durumu Not Arrived, Checked In ve No Show arasında değişir; Confirmed veya Tentative bilgisi değişmez."],
      ["Excel Dışa Aktarma","Reports → Export Table Plan gerçek bir .xlsx dosyası üretir. Tek HTML dosyasının kullandığı Excel motorunun ilk kez yüklenmesi için internet gerekir."],
      ["Table Plan Çalışma Kitabını Anlama","TABLE PLAN sayfasında yatay grupta dört masa kartı bulunur. GUEST LIST bütün kayıtları, UNASSIGNED masası olmayanları gösterir. Refakatçi koltukları GUEST OF [ANA İSİM] olarak çıkar."]]},
    {id:"operations",title:"Günlük Kullanım ve Sorun Giderme",intro:"Arama, geçmiş ve yerel koruma özellikleriyle etkinlik planını kontrollü tutun.",items:[
      ["Arama","Üst arama isim, davet eden, masa ve koltuk bilgilerini bulur. Sonuç seçilince Seating açılır, masa seçilir ve vurgulanır. Guests ile Live Event ekranlarında ayrıca özel arama vardır."],
      ["Undo / Redo","Floor Plan içindeki Undo ve Redo; masa, mekân nesnesi ve referans katmanı düzenlemelerini kapsar. Bir alana yazı yazmıyorken Ctrl/Cmd+Z ve Ctrl/Cmd+Y kullanılabilir."],
      ["Yerel Kayıt Sınırları","Veriler yalnızca bu tarayıcı profilinde saklanır. Tarayıcı verilerini silmek, cihaz değiştirmek veya gizli mod kullanmak veriyi kaybettirebilir. Düzenli Excel alın; çok büyük referans görselleri kalıcı olmayabilir."],
      ["Yaygın Hatalar / Sorun Giderme","İçe aktarma çalışmazsa Name Surname eşleştirmesini ve kırmızı doğrulama mesajlarını düzeltin. Atama olmazsa boş koltuğu kontrol edin. Masa hareket etmiyorsa kilidini açın. Excel düğmesi çalışmazsa interneti kontrol edip tekrar deneyin."]]},
  ];
  function floorGuideVisual(lang){const tr=lang==="tr";return`<div class="manual-visual"><div class="visual-title">${tr?"Masa oluşturma ve düzenleme":"Create and edit a table"}</div><div class="mini-workspace"><div class="mini-panel"><div class="mini-row active">▭ ${tr?"Rectangle Table":"Rectangle Table"}</div><div class="mini-row">${tr?"Koltuklar: 6":"Seats: 6"}</div><div class="mini-row">${tr?"Add to Plan":"Add to Plan"} →</div></div><div class="mini-canvas"><div class="mini-table" style="left:32%;top:35%">T 01</div><div class="mini-table" style="left:61%;top:25%">T 02</div><div class="mini-stage">STAGE</div><span class="mini-callout" style="left:28%;top:12%">1. ${tr?"Seç":"Select"}</span></div><div class="mini-panel"><div class="mini-row"><b>SEATING</b></div><div class="mini-row">− &nbsp; <b>6</b> &nbsp; +</div><div class="mini-row">2 &nbsp; 4 &nbsp; 6 &nbsp; 8</div></div></div></div>`}
  function excelGuideVisual(lang){const tr=lang==="tr";return`<div class="manual-visual"><div class="visual-title">${tr?"Excel +N örneği":"Excel +N example"}</div><div class="excel-visual"><table class="excel-demo"><thead><tr><th>NAME SURNAME</th><th>ADDITIONAL GUESTS</th><th>STATUS</th><th>VIP</th></tr></thead><tbody><tr><td>KEREM SARICICEK</td><td>3</td><td>Confirmed</td><td>VIP</td></tr><tr><td>KEREM SARICICEK +3</td><td></td><td>Confirmed</td><td>VIP</td></tr></tbody></table><div class="math-callout"><b>1 ${tr?"ana misafir":"primary guest"}</b><span>+</span><b>3 ${tr?"ek misafir":"additional guests"}</b><span>=</span><b>4 TOTAL PAX</b></div></div></div>`}
  function seatingGuideVisual(lang){const tr=lang==="tr";return`<div class="manual-visual"><div class="visual-title">${tr?"Dört gerçek koltuk ayırma":"Reserving four physical seats"}</div><div class="excel-visual"><table class="excel-demo"><tbody><tr><th>S1</th><td>KEREM SARICICEK</td></tr><tr><th>S2</th><td>GUEST OF KEREM SARICICEK</td></tr><tr><th>S3</th><td>GUEST OF KEREM SARICICEK</td></tr><tr><th>S4</th><td>GUEST OF KEREM SARICICEK</td></tr><tr><th>S5</th><td>${tr?"Boş":"Empty"}</td></tr><tr><th>S6</th><td>${tr?"Boş":"Empty"}</td></tr></tbody></table></div></div>`}
  function workbookGuideVisual(lang){const tr=lang==="tr";return`<div class="manual-visual"><div class="visual-title">${tr?"Table Plan — her yatay grupta dört kart":"Table Plan — four cards per horizontal group"}</div><div class="card-workbook">${[1,2,3,4].map(n=>`<div class="excel-card"><h4>T ${String(n).padStart(2,"0")}</h4><div><span>S1</span><span>${n===1?"KEREM SARICICEK":""}</span></div><div><span>S2</span><span></span></div><div><span>TOTAL</span><span>${n===1?"1":"0"}</span></div></div>`).join("")}</div></div>`}
  function manualVisual(type,lang){if(type==="floor")return floorGuideVisual(lang);if(type==="excel")return excelGuideVisual(lang);if(type==="seating")return seatingGuideVisual(lang);if(type==="workbook")return workbookGuideVisual(lang);return""}
  function renderGuide(){const lang=ui.guideLang,data=lang==="tr"?GUIDE_TR:GUIDE_EN,root=document.getElementById("guideRoot"),title=lang==="tr"?"Kullanıcı Kılavuzu":"User Guide";root.innerHTML=`<aside class="guide-nav"><div class="guide-brand"><strong>MERIT EVENT MAKER</strong><span>${title}</span></div>${data.map(s=>`<a href="#guide-${s.id}">${esc(s.title)}</a>`).join("")}</aside><section class="guide-main"><header class="guide-top"><h2>${title}</h2><div class="guide-actions"><div class="lang-toggle"><button data-guide-lang="en" class="${lang==="en"?"active":""}">EN</button><button data-guide-lang="tr" class="${lang==="tr"?"active":""}">TR</button></div><button class="btn" data-guide-print>${icon("print")}${lang==="tr"?"Yazdır / PDF Kaydet":"Print / Save Guide"}</button><button class="btn icon-only" data-guide-close title="Close">${icon("x")}</button></div></header><div class="guide-content"><div class="guide-hero"><div class="kicker">MERIT ENTERTAINMENT · EVENT MAKER</div><h1>${title}</h1><p>${lang==="tr"?"Etkinlik oluşturma, salon planı, Excel içe aktarma, çok kişili misafir kayıtları, oturma düzeni, canlı giriş ve operasyon Excel'i için adım adım başvuru dokümanı.":"Step-by-step reference for event creation, floor plans, Excel import, multi-pax guest records, seating, live arrivals and the operational workbook."}</p></div>${data.map(s=>`<section class="manual-section" id="guide-${s.id}"><h2>${esc(s.title)}</h2><p>${esc(s.intro)}</p><ol class="manual-list">${s.items.map(([h,p])=>`<li class="manual-item"><h3>${esc(h)}</h3><p>${esc(p)}</p></li>`).join("")}</ol>${manualVisual(s.visual,lang)}</section>`).join("")}<div class="guide-tip">${lang==="tr"?"Önemli: Çalışma verileri bu tarayıcıda yerel saklanır. Her büyük düzenlemeden sonra Table Plan Excel çıktısı alın.":"Important: Working data is stored locally in this browser. Export the Table Plan workbook after every major planning session."}</div></div></section>`;root.querySelectorAll("[data-guide-lang]").forEach(b=>b.onclick=()=>{ui.guideLang=b.dataset.guideLang;renderGuide()});root.querySelector("[data-guide-close]").onclick=()=>document.getElementById("guideDialog").close();root.querySelector("[data-guide-print]").onclick=()=>window.print()}
  function openGuide(){renderGuide();document.getElementById("guideDialog").showModal()}

  window.addEventListener("keydown",e=>{const editing=["INPUT","TEXTAREA","SELECT"].includes(document.activeElement?.tagName);if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"&&!editing){e.preventDefault();e.shiftKey?redoCanvas():undoCanvas()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="y"&&!editing){e.preventDefault();redoCanvas()}if(e.key==="Delete"&&!editing&&ui.screen==="workspace"&&ui.tab==="floor"&&ui.selectedObjectId)deleteSelectedObject(activeEvent());if(e.key==="Escape"&&ui.screen==="workspace"&&(ui.tab==="floor"||ui.tab==="seating")){ui.selectedObjectId=null;ui.highlightId=null;render()}});
  window.addEventListener("beforeunload",()=>saveState());
  render();
